### ISSUE TITLE
Not an issue: Join forces

### ISSUE THREAD

**Issue by Endogen** [izanmubarak/Cryptora#3]
Hey,

i've basically done the same as you. I wrote a Telegram bot for crypto. It's a bit more complex then your bot and i wanted to ask if you could imagine to join forces and maybe work on my bot too?

If you want to take a look: https://github.com/Endogen/OpenCryptoBot
If you are not interested, then please feel free to close the "issue" 😄 

Cheers,
Endo

**Comment by izanmubarak** [comment]
Hey I emailed you to follow up, let's continue the discussion there!
